version: "2.2" # optional since v1.27.0
services:

  elasticsearch:
    image: elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - internat

  kibana:
    image: kibana:7.12.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks: 
      - internat

networks:
  internat: {}
